website/views.py
from flask import Blueprint, render_template, flash, redirect, request, jsonify
from .models import Product, Cart, Order, db, CustomerContact, FarmerContact, Wishlist
from flask_login import login_required, current_user
from . import db
from intasend import APIService
from .forms import CustomerContactForm, FarmerContactForm

views = Blueprint('views', __name__)

API_PUBLISHABLE_KEY = 'ISPubKey_test_14e60f63-da53-4b92-9efd-ad0523eab4e6'

API_TOKEN = 'ISSecretKey_test_89b28112-9d26-4e8f-9c18-43b083cb79be'

#home
@views.route('/')
def home():

    items_true = Product.query.filter_by(flash_sale=True)
    items_false = Product.query.filter_by(flash_sale=False)

    return render_template('home.html', items_true=items_true, items_false=items_false, 
                           cart=Cart.query.filter_by(customer_link=current_user.id).all()
                           if current_user.is_authenticated else [], 
                           wishlist=Wishlist.query.filter_by(customer_link=current_user.id).all()
                           if current_user.is_authenticated else [])


#add_to_wishlist
@views.route('/add-to-wishlist/<int:item_id>')
@login_required
def add_to_wishlist(item_id):
    item_to_add = Product.query.get(item_id)
    if not item_to_add:
        flash('Product not found.')
        return redirect(request.referrer)

    if Wishlist.query.filter_by(product_link=item_id, customer_link=current_user.id).first():
        flash('Product already in your wishlist.')
        return redirect(request.referrer)

    new_wishlist_item = Wishlist()
    new_wishlist_item.product_link = item_to_add.id
    new_wishlist_item.customer_link = current_user.id

    try:
        db.session.add(new_wishlist_item)
        db.session.commit()
        flash('Product added to wishlist.')
    except Exception as e:
        print('Error adding product to wishlist:', e)
        flash('Failed to add product to wishlist.')

    return redirect(request.referrer)


#wishlist
@views.route('/wishlist')
@login_required
def wishlist():
    wishlist_items = Wishlist.query.filter_by(customer_link=current_user.id).all()
    return render_template('wishlist.html', wishlist=wishlist_items, cart=Cart.query.filter_by(customer_link=current_user.id).all()
                           if current_user.is_authenticated else [])


#remove_from_wishlist
@views.route('/remove-from-wishlist', methods=['POST'])
@login_required
def remove_from_wishlist():
    item_id = request.form.get('item_id')
    wishlist_item = Wishlist.query.get(item_id)
    if not wishlist_item:
        flash('Wishlist item not found.')
        return redirect(request.referrer)

    try:
        db.session.delete(wishlist_item)
        db.session.commit()
        flash('Product removed from wishlist.')
    except Exception as e:
        print('Error removing product from wishlist:', e)
        flash('Failed to remove product from wishlist.')

    return redirect(request.referrer)


#add_to_cart
@views.route('/add-to-cart/<int:item_id>')
@login_required
def add_to_cart(item_id):
    item_to_add = Product.query.get(item_id)
    
    if item_to_add.in_stock <= 0:
        flash('This item is currently out of stock.')
        return redirect(request.referrer)

    item_exists = Cart.query.filter_by(product_link=item_id, customer_link=current_user.id).first()
    
    if item_exists:
        try:
            item_exists.quantity += 1
            db.session.commit()
            flash(f'Quantity of {item_exists.product.product_name} has been updated')
            return redirect(request.referrer)
        except Exception as e:
            print('Quantity not Updated', e)
            flash(f'Quantity of {item_exists.product.product_name} not updated')
            return redirect(request.referrer)

    new_cart_item = Cart()
    new_cart_item.quantity = 1
    new_cart_item.product_link = item_to_add.id
    new_cart_item.customer_link = current_user.id

    try:
        db.session.add(new_cart_item)
        db.session.commit()
        flash(f'{new_cart_item.product.product_name} added to cart')
    except Exception as e:
        print('Item not added to cart', e)
        flash(f'{new_cart_item.product.product_name} has not been added to cart')

    return redirect(request.referrer)


#cart
@views.route('/cart')
@login_required
def show_cart():
    cart = Cart.query.filter_by(customer_link=current_user.id).all()
    amount = 0
    for item in cart:
        amount += item.product.current_price * item.quantity

    return render_template('cart.html', cart=cart, amount=amount, total=amount+200, wishlist=Wishlist.query.filter_by(customer_link=current_user.id).all()
                           if current_user.is_authenticated else [])


#plus_cart
@views.route('/pluscart')
@login_required
def plus_cart():
    if request.method == 'GET':
        cart_id = request.args.get('cart_id')
        cart_item = Cart.query.get(cart_id)
        cart_item.quantity += 1
        db.session.commit()

        cart = Cart.query.filter_by(customer_link=current_user.id).all()

        amount = 0

        for item in cart:
            amount += item.product.current_price * item.quantity

        data = {
            'quantity': cart_item.quantity,
            'amount': amount,
            'total': amount + 200
        }

        return jsonify(data)


#minus_cart
@views.route('/minuscart')
@login_required
def minus_cart():
    if request.method == 'GET':
        cart_id = request.args.get('cart_id')
        cart_item = Cart.query.get(cart_id)

        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            db.session.commit()
        else:

            db.session.delete(cart_item)
            db.session.commit()

        cart = Cart.query.filter_by(customer_link=current_user.id).all()

        amount = 0

        for item in cart:
            amount += item.product.current_price * item.quantity

        data = {
            'quantity': cart_item.quantity if cart_item.quantity > 0 else 0,
            'amount': amount,
            'total': amount + 200
        }

        return jsonify(data)


#remove_from_cart
@views.route('/remove-from-cart', methods=['POST'])
@login_required
def remove_from_cart():
    cart_id = request.form.get('cart_id')
    cart_item = Cart.query.get(cart_id)

    if not cart_item:
        flash('Cart item not found.', 'error')
        return redirect(request.referrer)

    try:
        product_name = cart_item.product.product_name
        db.session.delete(cart_item)
        db.session.commit()
        flash(f'{product_name} removed from cart.', 'success')
    except Exception as e:
        print('Error removing product from cart:', e)
        flash('Failed to remove product from cart.', 'error')

    return redirect(request.referrer)


#place_order
@views.route('/place-order')
@login_required
def place_order():
    customer_cart = Cart.query.filter_by(customer_link=current_user.id).all()
    if customer_cart:
        try:
            total = 0
            total_quantity = 0
            
            for item in customer_cart:
                total += item.product.current_price * item.quantity
                total_quantity += item.quantity

            items_exceeding_stock = [item for item in customer_cart if item.quantity > item.product.in_stock]
            if items_exceeding_stock:
                
                if len(items_exceeding_stock) == 1:
                    flash(f"The quantity of {items_exceeding_stock[0].product.product_name} exceeds the available stock.")
                else:
                    flash(f"The quantities of {', '.join([item.product.product_name for item in items_exceeding_stock])} exceed the available stock.")
                return redirect('/cart')  

            service = APIService(token=API_TOKEN, publishable_key=API_PUBLISHABLE_KEY, test=True)
            create_order_response = service.collect.mpesa_stk_push(phone_number='254-5530808', email=current_user.email,
                                                                   amount=total + 200, narrative='Purchase of goods')

            for item in customer_cart:
                new_order = Order()
                new_order.quantity = item.quantity
                new_order.price = item.product.current_price
                new_order.status = create_order_response['invoice']['state'].capitalize()
                new_order.payment_id = create_order_response['id']

                new_order.product_link = item.product_link
                new_order.customer_link = item.customer_link

                db.session.add(new_order)

                product = Product.query.get(item.product_link)

                product.in_stock -= item.quantity

                db.session.delete(item)

                db.session.commit()

            flash('Order Placed Successfully')

            return redirect('/orders')
        except Exception as e:
            print(e)
            flash('Order not placed')
            return redirect('/')
    else:
        flash('Your cart is Empty')
        return redirect('/')


#orders
@views.route('/orders')
@login_required
def order():
    orders = Order.query.filter_by(customer_link=current_user.id).all()
    return render_template('orders.html', orders=orders, cart=Cart.query.filter_by(customer_link=current_user.id).all()
                           if current_user.is_authenticated else [], wishlist=Wishlist.query.filter_by(customer_link=current_user.id).all()
                           if current_user.is_authenticated else [])


@views.route('/search', methods=['GET', 'POST'])
def search():
    if request.method == 'POST':
        search_query = request.form.get('search')
        items = Product.query.filter(Product.product_name.ilike(f'%{search_query}%')).all()
        return render_template('search.html', items=items, cart=Cart.query.filter_by(customer_link=current_user.id).all()

website/templates/add_shop_items.html
{% extends 'base.html' %}

{% block title %} Add Shop Items {% endblock %}


{% block body %}

<style>
    .td{
        width: 120px;
    }
</style>
<div class="my-5">



<h1 class="text-center mb-5" style="color: rgb(0, 0, 0); margin-top: -30px;"> Add shop Items</h1>

<table class="table table-dark table-hover" style="margin-top: -30px;">
    <thead>
        <tr>
            <th scope="col">Product Name</th>
            <th scope="col">Previous Price</th>
            <th scope="col">Current Price</th>
            <th scope="col">In Stock</th>

            <th scope="col">Unit</th> 
            <th scope="col">Small Unit</th> 
            <th scope="col">Picture</th>
            <th scope="col">Flash Sale</th>
            <th scope="col">Add</th>

        </tr>
    </thead>

    <tbody>
        <tr>
            <form action="" method="POST", enctype="multipart/form-data" id="addShopItemForm">
                {{ form.hidden_tag() }}

                <td>{{ form.product_name }}</td>
                <td>{{ form.previous_price (class="td")}}</td>
                <td>{{ form.current_price (class="td")}}</td>
                <td>{{ form.in_stock (class="td")}}</td>

                <td>{{ form.unit_of_measurement }}</td> 
                <td><input type="text" id="small_unit_of_measurement" name="small_unit_of_measurement" class="td" readonly></td>

                <td>{{ form.product_picture() }}</td>
                <td>{{ form.flash_sale }}</td>
                <td>{{ form.add_product() }}</td>
            </form>
        </tr>
    </tbody>
</table>
</div>


<script>
    
    var unitField = document.getElementById("unit_of_measurement");
    var smallUnitField = document.getElementById("small_unit_of_measurement");

    
    function updateSmallUnit() {
        var selectedUnit = unitField.value;
        var smallUnit = "";
        
        switch (selectedUnit) {
            case "pieces":
                smallUnit = "Piece";
                break;
            case "kilos":
                smallUnit = "Kg";
                break;
            case "liters":
                smallUnit = "Liter";
                break;
            default:
                smallUnit = "";
                break;
        }
        
        smallUnitField.value = smallUnit;
    }
    
    unitField.addEventListener("change", updateSmallUnit);

    updateSmallUnit();
</script>

{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js" ></script>


    <script src="https://kit.fontawesome.com/e24507d923.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.5/font/bootstrap-icons.min.css" />


    <link rel="stylesheet" href="{{ url_for('static', filename='css/all.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">

    <title>Food Blessing | {% block title %} {% endblock %}</title>
    <style>

    
      #page-container {
  position: relative;
  min-height: 100vh;
}

#content-wrap {
  padding-bottom: 4.0rem;    /* Footer height */
}
      .footer {
        position: absolute;
  bottom: 0;
  width: 100%;
  height: 3.0rem;
}

    </style>
</head>
<body style="background-color: #309061;">

  <div id="page-container">
    <div id="content-wrap">


    <!-- navbar section -->
    <nav class="navbar navbar-expand-lg" style="background-color: rgb(239, 192, 134);">
      <div class="container-fluid">
        <a class="navbar-brand" href="/" style="color: #06038d; font-size: 30px; margin-right: -2px;">
          <i class="fa-solid fa-carrot"></i>
          
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse " id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/" style="font-family: cursive; font-size: 30px;">Food Blessing</a>
            </li>

            <li class="nav-item" style="margin-left: 50px; "></li>
              <a class="nav-link text-black" style="margin-top: 10px;" href="/about-us" style="font-size: 19px;">About Us</a>
            </li>

            <li class="nav-item">
              <a class="nav-link text-black" style="margin-top: 10px;" href="/contact-us" style="font-size: 19px;">Contact us</a>
              
            </li>
          </ul>

          <form class="d-flex" role="search" action="/search" style="margin-right: 150px;" method="POST">
            <input class="form-control me-2" name="search" type="search" placeholder="Search" aria-label="Search" style="width: 350px;">
            <button class="btn" type="submit" >Search</button>
          </form>
        </div>

        


        <ul class="navbar-nav me-auto mb-2 mb-lg-0">

          <li class="nav-item mx-2" id="items">

            {% if cart | length < 1 %}
            <a class="nav-link text-black" href="/cart"><span class="badge bg-success"></span> Cart
              <i class="fa-solid fa-cart-shopping"></i>
            </a>
            {% else %}
            <a class="nav-link text-black" href="/cart"><span class="badge bg-success"></span> Cart
              <i class="bi bi-{{ cart | length }}-square-fill"></i>
            </a>

            {% endif %}


          </li>

          <li class="nav-item mx-2" id="items">
            {% if wishlist | length < 1 %}
            <a class="nav-link text-black" href="/wishlist">
              <span class="badge bg-success"></span> WishList
              <i class="fa-solid fa-heart"></i>
            </a>
            {% else %}
            <a class="nav-link text-black" href="/wishlist">
              <span class="badge bg-success"></span> WishList
              <i class="bi bi-{{wishlist | length}}-square-fill heart-icon"></i>
            </a>
            {% endif %}
          </li>
          


          <li class="nav-item dropdown mx-2">
            <a class="nav-link dropdown-toggle text-black" href="#" role="button", id="profileDropdown"
            data-bs-toggle="dropdown" aria-hidden="false">
              Account
            </a>
            <ul class="dropdown-menu "  aria-labelledby="profileDropdown">


              {% if current_user.is_authenticated %}
              <li><a class="dropdown-item" href="/profile">Profile <i class="fa-solid fa-user"></i></a></li>
              <li><a class="dropdown-item" href="/orders">Orders <i class="fa-solid fa-truck-fast"></i></a></li>
              <li><a class="dropdown-item" href="/feedback">Feedback <i class="fa-solid fa-comment-dots"></i></a></li>
              <li><a class="dropdown-item" href="/logout">Log Out <i class="fa-solid fa-right-from-bracket"></i></a></li>
              

              {% else %}

              <li><a class="dropdown-item" href="/login">Login <i class="fa-solid fa-right-to-bracket"></i></a></li>

              {% endif %}

            </ul>

          </li>

        </ul>


      </div>
    </nav>


    {% for message in get_flashed_messages() %}

    <div class="alert alert-success alert-dismissible fade show" role="alert" style="margin-top: 5px;">
        <strong>{{ message }}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

    </div>
    {% endfor %}

    {% block body %}


    {% endblock %}

  </div>
    <footer class="container-fluid  text-center p-3 mt-5 footer" style="background-color: rgb(239, 192, 134); color: rgb(0, 0, 0);">
      <a href="https://freshpizza.netlify.app" style="color: rgb(0, 0, 0);">Food Blessing</a> | <span>
        <i class="fa-sharp fa-regular fa-copyright"></i></span> 2024 All rights reserved

    </footer>

    <script src="{{ url_for( 'static', filename='js/owl.carousel.min.js') }}"></script>
    <script src="{{ url_for( 'static', filename='js/all.min.js') }}"></script>
    <script src="{{ url_for( 'static', filename='js/jquery.js') }}"></script>

    <script src="{{ url_for( 'static', filename='js/myScript.js') }}"></script>


  </div>
</body>
</html>

website/templates/change_password.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}


{% block body %}

<div class="my-5">

    <h1 class="text-center mb-5" style="color: rgb(0, 0, 0); margin-top: -40px;"> Change password</h1>

    <div class="container">
        <div class="row justify-content-center">
<div class="col-sm-5 " style="background-color: rgb(250, 219, 181); border-radius: 10px; margin-top: 20px; margin-top: -30px;">

    <form style="padding: 30px;" method="POST">
    
        {{ form.hidden_tag() }}

        <div class="mb-3">
            <label for="exampleInputEmail" class="form-label"> {{ form.current_password.label }}</label>
            {{ form.current_password (class="form-control me-2", placeholder="Current password") }}
        </div>

        <div class="mb-3">
            <label for="exampleInputEmail" class="form-label"> {{ form.new_password.label }}</label>
            {{ form.new_password (class="form-control me-2", placeholder="New password")}}
        </div>

        <div class="mb-3">
            <label for="exampleInputEmail" class="form-label"> {{ form.confirm_new_password.label }}</label>
            {{ form.confirm_new_password (class="form-control me-2", placeholder="Confirm new password")}}
        </div>

        <div class="d-grid">
        {{ form.change_password (class="btn btn-primary ", style="background-color: #06038d") | safe}}
        </div>
    
    </form>

</div>
</div>
</div>

</div>

{% endblock %}

website/templates/contact_us.html
{% extends 'base.html' %}

{% block title %} Contact Us {% endblock %}

{% block body %}

<style>
    .form1 {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100%;
}
.form {
    max-width: 400px;
    padding: 20px;
    border-radius: 10px;
    background-color: #f8f9fa;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
}
</style>

<h2 class="text-center" style="padding-top: 15px;">Farmer Contact Us</h2>
<hr style="border-top: 5px dotted; width: 36%; margin: auto;">

<div class="container my-5 form1">
    <div class="row" style="margin-top: -25px;"> 
        <div class="col-md-6">
            
            <div class="form " style="width: 550px; max-width: 900px; background-color: rgb(250, 219, 181);">
            <form method="POST" action="/contact/farmer">
                {{ farmer_form.hidden_tag() }}
                <div class="form-group">
                    {{ farmer_form.name.label }} {{ farmer_form.name(class="form-control") }}
                </div>
                <div class="form-group">
                    {{ farmer_form.email.label }} {{ farmer_form.email(class="form-control") }}
                </div>
                <div class="form-group">
                    {{ farmer_form.product.label }} {{ farmer_form.product(class="form-control") }}
                </div>
                <div class="form-group">
                    {{ farmer_form.quantity.label }} {{ farmer_form.quantity(class="form-control") }}
                </div>
                <div class="form-group">
                    {{ farmer_form.unit.label }} {{ farmer_form.unit (class="form-select form-control")}}
                </div>
                <div class="form-group">
                    {{ farmer_form.description.label }} {{ farmer_form.description(class="form-control", placeholder= "Type your description here...") }}
                </div>
                <button type="submit" class="btn btn-primary" style="background-color: #06038d; border-color: #06038d; margin-top: 10px;">Submit</button>
            </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

website/templates/contact_us_entry.html
{% extends 'base.html' %}

{% block title %} Shop Items {% endblock %}


{% block body %}

<style>
    th, td {
  
  border-left: solid 1px grey;
}
</style>
<div class="my-5">

    <h1 class="text-center mb-5" style="color: rgb(0, 0, 0); margin-top: -40px;"> contact us entry</h1>



<table class="table table-dark table-hover" style="margin-top: -30px;">
    <thead>
        <tr class="text-center">
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th scope="col">Product</th>
            <th scope="col">Quantity</th>
            <th scope="col">Unit</th>
            <th scope="col">Description</th>
            
        </tr>
    </thead>

    <tbody>
        {% for item in items %}
            

        <tr>
            <th scope="row">{{ item.id }}</th>
            <td>{{ item.name }}</td>
            <td>{{ item.email }}</td>
            <td>{{ item.product }}</td>
            <td>{{ item.quantity }}</td>
            <td>{{ item.unit }}</td>
            <td>{{ item.description }}</td>
            
            

        </tr>

            
        {% endfor %}
    </tbody>
</table>

</div>





{% endblock %}

website/templates/login.html
{% extends 'forms.html' %}

{% block title %} Login {% endblock %}

{% block body %}

<style>
    /* Custom CSS for login form */

.base-content {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100%;
}

.form {
    max-width: 400px;
    padding: 20px;
    border-radius: 10px;
    background-color: #f8f9fa;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
}

.form h3 {
    text-align: center;
    margin-bottom: 20px;
}

.form hr.first {
    margin-bottom: 20px;
}

.form-group {
    margin-bottom: 20px;
}

.form-group label {
    font-weight: bold;
}

.form-control {
    width: 100%;
    padding: 10px;
    border: 1px solid #ced4da;
    border-radius: 5px;
    box-sizing: border-box;
    border-color: white; /* Default border color */
}

form-control:focus {
    border-color: #007bff; /* Focus border color */
}

.buttons {
    display: flex;
    justify-content: space-between;
    align-items: center;
}

.btn {
    padding: 10px 20px;
    border: none;
    border-radius: 5px;
    cursor: pointer;
}

.btn-primary {
    background-color: #007bff;
    color: #fff;
}

.btn-secondary {
    background-color: #6c757d;
    color: #fff;
}

.btn:hover {
    opacity: 0.8;
}

.form-control::placeholder {
    color: rgb(113, 113, 113);
}
</style>

<!-- Login section start -->

<section  id="base-signup" style="padding-top: 50px;">
    <h1 class="text-center">login page</h1>
    <div class="base-content">
        
        <div class="form" style="width: 500px; background-color: rgb(250, 219, 181);">
            <h3>Login to start <br> Shopping</h3>
            
            <hr class="first">
            <form method="POST">
                {{ form.hidden_tag() }}

                <div class="form-group">
                    <label for="email">Email Address</label>
                    {{ form.email(class="form-control", placeholder="Enter your email") }}
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    {{ form.password(class="form-control", placeholder="Enter your password") }}
                </div>

                <div class="buttons">
                    <a href="/sign-up" class="btn btn-secondary">Sign Up</a>
                    {{ form.submit(class="btn btn-primary") }}
                </div>
            </form>
        </div>
    </div>
</section>

{% endblock %}

website/templates/order_update.html
{% extends 'base.html' %}

{% block title %} Update Order {% endblock %}


{% block body %}

<div class="my-5">

    <h1 class="text-center mb-5" style="color: rgb(0, 0, 0); margin-top: -40px;"> Order status</h1>

<table class="table table-dark table-hover" style="margin-top: -30px;">
    <thead>
        <tr>
            <th scope="col">Order Status</th>
            <th scope="col">Order Status</th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <form action="" method="POST" enctype="multipart/form-data">
                {{ form.hidden_tag() }}

                <td>{{ form.order_status }}</td>
                <td>{{ form.update() }}</td>
            </form>
        </tr>
    </tbody>
</table>

</div>

{% endblock %}

website/templates/search.html
{% extends 'base.html' %}

{% block title %} Search {% endblock %}


{% block body %}
<style>
    .form1 {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100%;
}
</style>

{% if items | length < 1 %}
<h3 class="text-center mb-5" style="color: rgb(0, 0, 0); margin-top: 10px;">No Items Match your Search query</h3>

{% else %}

<h3 class=" container text-center mb-5" style="color: rgb(0, 0, 0); margin-top: 10px;">Searched Results</h3>


<!-- Sorting options -->

<div class="container text-center form1" style="  margin-top: -20px;  margin-bottom: 20px; ">
    <div class="row " style="  padding: -10px; width: 470px; height: 50px; background-color: rgb(250, 219, 181); border-radius: 10px;" >
        <div class="row form1" style="margin-right: -40px; box-sizing:content-box;">
            <div class="col " >
                
                <a style="background-color: #ff671f; /* background-color: #ff671f; */
                padding: 5px;
                border-radius: 10px;
                text-decoration: none;
                color: white;" href="{{ url_for('views.search', sort='price_low_high') }}">Price (Low to High)</a>
                
                <a style="background-color: #ff671f; /* background-color: #ff671f; */
                padding: 5px;
                border-radius: 10px;
                text-decoration: none;
                color: white;" href="{{ url_for('views.search', sort='price_high_low') }}">Price (High to Low)</a>
                 
                <a style="background-color: #ff671f; /* background-color: #ff671f; */
                padding: 5px;
                border-radius: 10px;
                text-decoration: none;
                color: white;" href="{{ url_for('views.search', sort='name') }}">Name</a>
                
                <a style="background-color: #ff671f; /* background-color: #ff671f; */
                padding: 5px;
                border-radius: 10px;
                text-decoration: none;
                color: white;" href="{{ url_for('views.search', sort='availability') }}">Availability</a>
                
            </div>
        </div>
    </div>
</div>

<div class="container text-center" style="width: 1130px;">
    <div class="row col-md-10" style="width: 1096px; margin: 8px;  background-color: #ffffff; border-radius: 10px;" id="column">

        {% for item in items %}

        <div class="col" style=" height: 330px; width: 200px; max-width: 209px; background-color:rgb(250, 219, 181); margin: 5px; border-radius: 10px;">

            <img src="{{ item.product_picture }}" alt="" style="height: 180px; width: 180px; object-fit:contain;">

            <div class="row" style="margin-top: 5px;">
                <h6 style="color: gray;">{{ item.product_name }}</h6>
            </div>

            <div class="row" style="margin-top: 10px;">

                <div class="col" style="padding: 5px;">
                    
                    <h5  style="font-weight: 600; font-family: 'Times New Roman', Times, serif; margin-left: -11px; margin-right: -25px;">₹ {{ item.current_price }} {{ item.small_unit_of_measurement }}</h5>
                    <strike><p style="color: gray; margin-left: -10px; margin-right: -20px;">₹ {{ item.previous_price}} {{ item.small_unit_of_measurement }}</p></strike>
                    
                </div>
                
                <div class="col text-center" style="margin-top: 10px; padding-top: 10px;">
                    
                    {% if item.in_stock > 0 %}
                        <a href="/add-to-cart/{{ item.id }}" style="background-color: #ff671f; margin-left: -25px; margin-right: -30px;">Add to cart</a>
                        
                    {% else %}
                        <p style="background-color: red; color: white; width: 104px; height: 42px; padding-top: 10px; border-radius: 10px; margin-top: -10px; margin-right: -7px;">Out of Stock</p>
                    {% endif %}
                </div>

            </div>

           

            <div class="row" style="margin-top: -5px;">
                {% if item.in_stock == 1 %}
                    <p>{{ item.in_stock }} {{ item.small_unit_of_measurement }} Left</p>

                {% elif item.in_stock > 0 %}
                    <p>{{ item.in_stock }} {{ item.unit_of_measurement }} Left</p>
                    
                {% else %}
                    <p style="color: red;">Come back later</p> 
                {% endif %}
            </div>
        </div>

        {% endfor %}

    </div>
</div>


{% endif %}


{% endblock %}